import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import requests
import json

# ── Config from GitHub Secrets ──────────────────────────────────────
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
GMAIL_ADDRESS = os.environ["GMAIL_ADDRESS"]
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]
RECIPIENT_EMAIL = os.environ.get("RECIPIENT_EMAIL", GMAIL_ADDRESS)

# ── Your prompt (edit this or load from env) ────────────────────────
PROMPT = os.environ.get("GEMINI_PROMPT", "Give me a daily briefing on the latest developments in AI, supply chain technology, and enterprise SaaS. Keep it concise and actionable.")


def call_gemini(prompt: str) -> str:
    """Call Gemini API and return the response text."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={GEMINI_API_KEY}"

    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": 0.7,
            "maxOutputTokens": 4096,
        },
    }

    response = requests.post(url, json=payload, timeout=60)
    response.raise_for_status()

    data = response.json()
    return data["candidates"][0]["content"]["parts"][0]["text"]


def send_email(subject: str, body: str):
    """Send an email via Gmail SMTP using an App Password."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = RECIPIENT_EMAIL

    # Plain text fallback
    msg.attach(MIMEText(body, "plain"))

    # HTML version (wraps Gemini markdown-ish output in basic styling)
    html_body = f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; 
                 max-width: 680px; margin: 0 auto; padding: 24px; 
                 color: #1a1a1a; line-height: 1.6;">
        <h2 style="border-bottom: 1px solid #e0e0e0; padding-bottom: 8px; 
                    font-weight: 500; color: #111;">
            {subject}
        </h2>
        <div style="white-space: pre-wrap; font-size: 15px;">
{body}
        </div>
        <hr style="border: none; border-top: 1px solid #e0e0e0; margin-top: 32px;">
        <p style="font-size: 12px; color: #888;">
            Generated by Gemini API · {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
        </p>
    </body>
    </html>
    """
    msg.attach(MIMEText(html_body, "html"))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, RECIPIENT_EMAIL, msg.as_string())


def main():
    today = datetime.now().strftime("%A, %B %d, %Y")
    print(f"🚀 Running daily Gemini automation — {today}")

    print("📡 Calling Gemini API...")
    result = call_gemini(PROMPT)
    print(f"✅ Got response ({len(result)} chars)")

    subject = f"Daily Gemini Brief — {today}"
    print(f"📧 Sending email to {RECIPIENT_EMAIL}...")
    send_email(subject, result)
    print("✅ Email sent successfully!")


if __name__ == "__main__":
    main()
